<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon" href="style/images/favicon.png">
<title>Four Phoneix</title>
  <link rel="canonical" href="https://www.fourphoenix.com/ecommerce-seo" />
  <meta name="description" content="Ecommerce SEO" />
<link rel="stylesheet" type="text/css" href="style/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="style/css/plugins.css">
<link rel="stylesheet" type="text/css" href="style/revolution/css/settings.css">
<link rel="stylesheet" type="text/css" href="style/revolution/css/layers.css">
<link rel="stylesheet" type="text/css" href="style/revolution/css/navigation.css">
<link rel="stylesheet" type="text/css" href="style/type/type.css">
<link rel="stylesheet" type="text/css" href="style.css">
<link rel="stylesheet" type="text/css" href="style/css/color/purple.css">
</head>
<body>
<div class="content-wrapper">
<?php include 'header.php';?>

<div class="wrapper image-wrapper bg-image page-title-wrapper inverse-text" data-image-src="style/images/bg6.jpg">
<div class="container inner text-center">
<div class="space90"></div>
<h1 class="page-title">India's Ecommerce SEO Services</h1>
</div>
<!-- /.container -->
</div>
<!-- /.wrapper -->
<div class="wrapper white-wrapper">
<div class="container inner">
<div class="row align-items-center">
<!--/column -->
<div class="col-lg-12">
	<p>Increase Your Ecommerce Store's Traffic and Sales With India's Best Ecommerce SEO
Services!</p>
<p>Experience: 3+ Years</p>
<p>98 percent success rate Result-Oriented Strategy Highly Skilled Team of Digital
Marketers</p>
<h3 class="display-3">India's Result-Oriented Ecommerce SEO Services</h3>
<p>Four Phoenix can help you improve your ranking, earnings, and trustworthiness. We
endeavour to provide the best service possible for both you and us!</p>
<p>eCommerce retailers and SEO are becoming more and more in love. The more stores
that open in the virtual world, the more difficult it is for businesses to compete. If your
competitors' e-commerce success has piqued your interest, it's time to start looking for a
professional eCommerce solution for your business.</p>
<p>If you've been trying to figure out how to increase your sales and shop visits, it's time to
speak with an eCommerce SEO specialist for a road map to success. Anyone can claim
to be able to get you to the top, but only a few can keep their word.</p>
<p>Why? The reason for this is simple: eCommerce SEO is difficult. To fulfil the market's
difficulties and standards, it necessitates perseverance, measurement, planning, and
up-gradation.</p>
<p>At Four Phoenix, we follow through on our promises. We are a goal-oriented digital
marketing firm that includes eCommerce SEO in all of our digital marketing packages.
A team of experts manages every area of the online store's SEO, from keyword selection
to reporting. We understand the challenges of online marketing, particularly for
e-commerce shops. We have a staff that can supply your store with a complete
eCommerce SEO solution.</p>
</div>  
</div>
<!--/.row -->
</div>
<!-- /.container -->
</div>
<!-- /.wrapper -->
<div class="wrapper light-wrapper">
<div class="container inner">
<div class="row align-items-center">
<div class="col-lg-12">
	<h3 class="display-3">Why Is SEO Important for Ecommerce Stores?</h3>
	<h2 class="title-color color-gray">SEO services for e-commerce</h2> 
	<p>The money generated by any online store can be used to determine its success. And
visits to the stores are required to generate revenue. Though there are other avenues for
generating visitors, such as social media and paid advertising, when you look at the
larger picture of traffic and earnings, you'll notice that search engine traffic plays a
significant role in the store's earnings.</p>
<p>Now you might be thinking, "What's the big deal?" There are so many pros who do
eCommerce SEO that I could hire any of them.</p>
<p>This can be a turning point for your online store. Working with an online shop SEO
service provider who is well-versed, competent, and results-oriented may help you
increase your earnings and reputation, but any regular SEO service will provide you
initial glitz and glam but leave you with low sales and bad performance.</p>
</div>
<div class="col-lg-6 pr-60 pr-md-15">

<p>Four Phoenix provides a devoted, knowledgeable, and professional team of e-commerce
SEO experts who can help with e-commerce development and SEO services. With the
appropriate strategy, method, and approach, we can provide what you want, no matter
how big or little your company is or how new or old your brand is.</p>
<p>We don't offer a pre-made eCommerce SEO strategy with small tweaks; instead, we
start from the ground up and put in our best effort to build tactics and plans that will
yield the best results. We don't just say things; we do them. Our most important
motivator and asset are our satisfied customers.</p>
<p>Don't ponder and wait; every day that passes is a revenue loss. Join together with an
e-commerce SEO professional to receive the best SEO solution for your E-Commerce
store. Earn your success by giving your e-commerce store a robust base that allows it to
weather difficulties and changes without losing ground. Please contact one of our
executives to learn more about how we may help you.</p>
</div>
<div class="space30 d-none d-md-block d-lg-none"></div>
<div class="col-lg-6 play-wrapper light-gallery-wrapper text-center">
<img src="style/images/digital_marketing/e_commerce_seo_strategy.png" style="width: 30rem" alt="" />
</div>
<!--/column -->          
</div>
<!--/.row -->
</div>
<!-- /.container -->
</div>

<div class="wrapper white-wrapper">
      <div class="container inner">
        <div class="row align-items-center">
          <!--/column -->
           <div class="col-lg-6 play-wrapper light-gallery-wrapper text-center">
            <img src="style/images/digital_marketing/e_commerce_seo_cost.jpg" style="width: 30rem" alt="" />
                      </div>

                   <div class="space30 d-none d-md-block d-lg-none"></div>
          <div class="col-lg-6 pl-60 pl-md-15">
                       <h3 class="display-3">Cost of Ecommerce SEO Services</h3>
            <p>For your online store SEO marketing, take a look at our eCommerce SEO services
packages. Our online store SEO services work with a variety of platforms, including
Shopify, Wix, WordPress, BigCommerce, and others. Our adaptable SEO strategy allows
for customisation to match the needs of our clients. When selecting SEO services, keep
in mind that it is an investment rather than an expense for your company.</p>
<p>Our SEO services are comprehensive; we start with the basics, such as keyword research
and analysis, and work our way up to website conversion analysis to ensure that our
clients get the results they expect.</p>
<p>At Four Phoenix, we design SEO for eCommerce websites in a unique way.
SEO for eCommerce websites is a multi-faceted project. We work on the following
factors to make eCommerce SEO success for your store:</p>
<ul class="icon-list bullet-default">
              <li><i class="jam jam-arrow-right"></i>Content Service for Keyword Optimization</li>
              <li><i class="jam jam-arrow-right"></i>SEO plan for an online store that is tailored to your needs</li>
              <li><i class="jam jam-arrow-right"></i>Project management via the internet</li>
              <li><i class="jam jam-arrow-right"></i>Product description markup</li>
              <li><i class="jam jam-arrow-right"></i>Image optimization using keyword research</li>
              <li><i class="jam jam-arrow-right"></i>Reporting every month</li>	
            </ul> 
          </div>
          <!--/column -->          
        </div>
        <!--/.row -->
      </div>
      <!-- /.container -->
    </div>
    <!-- /.wrapper -->
   <div class="wrapper light-wrapper">
      <div class="container inner">
        <div class="row align-items-center">
          <!--/column -->
          <div class="col-lg-6 pr-60 pr-md-15">
                       <h3 class="display-3">How Can Four Phoenix Assist You With eCommerce Store SEO?</h3>
            <p>We are a full-service digital marketing agency. We don't mindlessly follow pre-made
e-commerce SEO strategies. We examine, comprehend, and then devise a strategy that
has the potential to improve your revenue generation and online branding.
It doesn't matter how big the store is; with the correct optimization strategy, every
product listed on the website may get the attention it deserves. If you're wondering why
you should trust us with your eCommerce SEO, here are a few reasons:</p>
<div id="accordion-2" class="accordion-wrapper simple">
<div class="card">
<div class="card-header" id="accordion-heading-2-1">
<h5>
<button class="collapsed" data-toggle="collapse" data-target="#accordion-collapse-2-1" aria-expanded="false" aria-controls="accordion-collapse-2-1">Our local SEO services assist you in creating local SEO friendly URLs.</button>
</h5>
</div>
<!-- /.card-header -->
<div id="accordion-collapse-2-1" class="collapse" aria-labelledby="accordion-heading-2-1" data-target="#accordion-2">
<div class="card-body">
<p>URLs are highly crucial in Local Business SEO, and if you don't know why, consult your
local SEO service provider. Our local SEO professionals develop URLs that include your
company's address.</p>
</div>
<!-- /.card-body -->
</div>
<!-- /.collapse -->
</div>
<!-- /.card -->
<div class="card">
<div class="card-header" id="accordion-heading-2-2">
<h5>
<button class="collapsed" data-toggle="collapse" data-target="#accordion-collapse-2-2" aria-expanded="false" aria-controls="accordion-collapse-2-2">Experiential Learning</button>
</h5>
</div>
<!-- /.card-header -->
<div id="accordion-collapse-2-2" class="collapse" aria-labelledby="accordion-heading-2-2" data-target="#accordion-2">
<div class="card-body">
<p>Each project is a major priority for us. Whatever your budget or store size, if we're on
board, we'll give the greatest e-commerce SEO solution for you. We've worked with
several brands in a variety of industries as a marketing partner.</p>
</div>
<!-- /.card-body -->
</div>
<!-- /.collapse -->
</div>
<!-- /.card -->
<div class="card">
<div class="card-header" id="accordion-heading-2-3">
<h5>
<button class="collapsed" data-toggle="collapse" data-target="#accordion-collapse-2-3" aria-expanded="false" aria-controls="accordion-collapse-2-3">Resource Team for Game-Changers</button>
</h5>
</div>
<!-- /.card-header -->
<div id="accordion-collapse-2-3" class="collapse" aria-labelledby="accordion-heading-2-3" data-target="#accordion-2">
<div class="card-body">
<p>eCommerce SEO is not a one-man show; to produce excellent results, you'll need a team
of experts in the field. Each aspect of store optimization is handled by a separate team.
This collaborative effort of best-in-class minds aids us in achieving the desired outcome.</p>
</div>
<!-- /.card-body -->
</div>
<!-- /.collapse -->
</div>
<!-- /.card -->
<div class="card">
<div class="card-header" id="accordion-heading-2-4">
<h5>
<button class="collapsed" data-toggle="collapse" data-target="#accordion-collapse-2-4" aria-expanded="false" aria-controls="accordion-collapse-2-4">There's Nothing to Hide</button>
</h5>
</div>
<!-- /.card-header -->
<div id="accordion-collapse-2-4" class="collapse" aria-labelledby="accordion-heading-2-4" data-target="#accordion-2">
<div class="card-body">
<p>We understand that this is your business; you've invested time and money in us, and
you're counting on us to help you achieve your marketing objectives. Every step of the
optimization process is communicated to our clients. Last but not least, our pricing
approach is transparent, with no hidden fees or additional charges that will be
discovered later.</p>
</div>
<!-- /.card-body -->
</div>
<!-- /.collapse -->
</div>
<!-- /.card -->
<div class="card">
<div class="card-header" id="accordion-heading-2-5">
<h5>
<button class="collapsed" data-toggle="collapse" data-target="#accordion-collapse-2-5" aria-expanded="false" aria-controls="accordion-collapse-2-5">Plan & Service Tailored to You</button>
</h5>
</div>
<!-- /.card-header -->
<div id="accordion-collapse-2-5" class="collapse" aria-labelledby="accordion-heading-2-5" data-target="#accordion-2">
<div class="card-body">
<p>When it comes to SEO, there is no such thing as a one-size-fits-all solution. Each project
has its own set of problems and strengths. We identify the fundamental issue, evaluate
the potential, examine the available resources, and then devise a strategy that will result
in significant increases in the number of visitors and money generated.</p>
</div>
<!-- /.card-body -->
</div>
<!-- /.collapse -->
</div>
<!-- /.card -->
</div>
          </div>
                             <div class="space30 d-none d-md-block d-lg-none"></div>

                     <div class="col-lg-6 play-wrapper light-gallery-wrapper text-center">
            <div class="img-blob blob7"><img src="style/images/digital_marketing/e_commerce_seo_assist.jpg" style="width: 30rem" alt="" /></div>
                      </div>

          <!--/column -->          
        </div>
        <!--/.row -->
      </div>
      <!-- /.container -->
    </div>

    <div class="wrapper white-wrapper">
      <div class="container inner">
        <div class="row align-items-center">
          <!--/column -->
          <div class="col-lg-12">
          	 <h3 class="display-3">Advantages of E-Commerce SEO</h3>
            <p>Any great e-commerce store will amaze you with how much time and money they put
into SEO. Despite the popularity of social media, the search engine remains one of the
most reliable ways to connect with a product or service. A well-designed e-commerce
SEO strategy may assist businesses in identifying promising leads, which can result in
increased sales and revenue.</p>
          </div>
           <div class="col-lg-6 play-wrapper light-gallery-wrapper text-center">
            <img src="style/images/digital_marketing/advantages.png" style="width: 30rem" alt="" />
            </div>

                   <div class="space30 d-none d-md-block d-lg-none"></div>
          <div class="col-lg-6 pl-60 pl-md-15">
<div id="accordion-3" class="accordion-wrapper simple">
<div class="card">
<div class="card-header" id="accordion-heading-3-1">
<h5>
<button class="collapsed" data-toggle="collapse" data-target="#accordion-collapse-3-1" aria-expanded="false" aria-controls="accordion-collapse-3-1">This is beneficial to revenue and sales.</button>
</h5>
</div>
<!-- /.card-header -->
<div id="accordion-collapse-3-1" class="collapse" aria-labelledby="accordion-heading-3-1" data-target="#accordion-3">
<div class="card-body">
<p>Visitors that come to your e-commerce store via a search engine result page are more
likely to purchase because they trust search results. SEO can help you attract more
customers to your store. If your e-commerce store isn't prepared to meet the needs of a
potential buyer, you risk losing the sale. Make that the store's user interface, product
itineraries, and payment gateway are all ready to meet the needs of visitors.</p>
</div>
<!-- /.card-body -->
</div>
<!-- /.collapse -->
</div>
<!-- /.card -->
<div class="card">
<div class="card-header" id="accordion-heading-3-2">
<h5>
<button class="collapsed" data-toggle="collapse" data-target="#accordion-collapse-3-2" aria-expanded="false" aria-controls="accordion-collapse-3-2">Optimize the entire product line to maximise profits</button>
</h5>
</div>
<!-- /.card-header -->
<div id="accordion-collapse-3-2" class="collapse" aria-labelledby="accordion-heading-3-2" data-target="#accordion-3">
<div class="card-body">
<p>E-commerce stores face several issues, one of which is their large size. It's difficult to
optimise each product for its potential clients when there are thousands of them.</p>
<p>However, using e-commerce SEO, you may optimise a product line to make it more
appealing to potential customers. There is a market to buy if you have a product to sell,
and e-commerce SEO bridges the gap between buyer and seller.</p>
</div>
<!-- /.card-body -->
</div>
<!-- /.collapse -->
</div>
<!-- /.card -->
<div class="card">
<div class="card-header" id="accordion-heading-3-3">
<h5>
<button class="collapsed" data-toggle="collapse" data-target="#accordion-collapse-3-3" aria-expanded="false" aria-controls="accordion-collapse-3-3">Give the store a solid foundation. With Natural Traffic</button>
</h5>
</div>
<!-- /.card-header -->
<div id="accordion-collapse-3-3" class="collapse" aria-labelledby="accordion-heading-3-3" data-target="#accordion-3">
<div class="card-body">
<p>Paid advertising and social media platforms can guarantee a steady stream of visitors
for a limited period and at a high cost, whereas organic search traffic guarantees a
steady stream of visitors. Ecommerce SEO is more long-term and offers a better return
on investment.</p>
</div>
<!-- /.card-body -->
</div>
<!-- /.collapse -->
</div>
<!-- /.card -->
<div class="card">
<div class="card-header" id="accordion-heading-3-4">
<h5>
<button class="collapsed" data-toggle="collapse" data-target="#accordion-collapse-3-4" aria-expanded="false" aria-controls="accordion-collapse-3-4">Buyers are more persuaded by organic search results.</button>
</h5>
</div>
<!-- /.card-header -->
<div id="accordion-collapse-3-4" class="collapse" aria-labelledby="accordion-heading-3-4" data-target="#accordion-3">
<div class="card-body">
<p>Visitors trust websites that rank high in the SERPs. It not only boosts credibility and
brand image, but it also encourages the searcher to visit the store to see how it is, what
items and services it offers, and how strong of a competitor it is. In a nutshell, an
organic search result is a genuine way to engage people.</p>
</div>
<!-- /.card-body -->
</div>
<!-- /.collapse -->
</div>
<!-- /.card -->
<div class="card">
<div class="card-header" id="accordion-heading-3-5">
<h5>
<button class="collapsed" data-toggle="collapse" data-target="#accordion-collapse-3-5" aria-expanded="false" aria-controls="accordion-collapse-3-5">Assists In Making Contact With Potential Visitors</button>
</h5>
</div>
<!-- /.card-header -->
<div id="accordion-collapse-3-5" class="collapse" aria-labelledby="accordion-heading-3-5" data-target="#accordion-3">
<div class="card-body">
<p>The SEO team's primary task is to identify keywords that can generate visitors with the
intent to purchase. The SEO team's job is to optimise the store for relevant keywords to
increase leads and revenue.</p>
<p>With hundreds of competitors vying for your business, skimping on SEO might result
in income loss. The buyers are willing to spend, but are you willing to bring them on
board?</p>
<p>Here, SEO can assist you in connecting with buyers who are looking to purchase things.
If you lose out on the chance to interact with them, there are plenty of others who will
gladly welcome them into your store. When you invest in e-commerce SEO, you're
paving the way for targeted and potential customers to find your store. Keep in mind
that SEO is an investment with a guaranteed return.</p>
<p>An eCommerce store's SEO differs from that of a traditional business. The essential
concept remains the same, which is to engage with organic visitors. Our e-commerce
SEO strategy is results-driven, and we use a process that focuses on key issues such as
fewer organic visits and lower keyword rankings.</p>
</div>
<!-- /.card-body -->
</div>
<!-- /.collapse -->
</div>
<!-- /.card -->
<div class="card">
<div class="card-header" id="accordion-heading-3-6">
<h5>
<button class="collapsed" data-toggle="collapse" data-target="#accordion-collapse-3-6" aria-expanded="false" aria-controls="accordion-collapse-3-6">Identifying and implementing keywords</button>
</h5>
</div>
<!-- /.card-header -->
<div id="accordion-collapse-3-6" class="collapse" aria-labelledby="accordion-heading-3-6" data-target="#accordion-3">
<div class="card-body">
<h3>Researching Keywords</h3>
<p>Finding keywords with promise is the first stage in our e-commerce store SEO. Our
e-commerce SEO specialists employ the most up-to-date techniques to analyse user
behaviour and determine which keywords to pursue. Following the selection of a
keyword, the next step is to put it on the store as well as other SEO strategies that can
result in major changes in ranking and, as a result, increased revenue.</p>
</div>
<!-- /.card-body -->
</div>
<!-- /.collapse -->
</div>

<div class="card">
<div class="card-header" id="accordion-heading-3-7">
<h5>
<button class="collapsed" data-toggle="collapse" data-target="#accordion-collapse-3-7" aria-expanded="false" aria-controls="accordion-collapse-3-7">Page Optimization for Products</button>
</h5>
</div>
<!-- /.card-header -->
<div id="accordion-collapse-3-7" class="collapse" aria-labelledby="accordion-heading-3-7" data-target="#accordion-3">
<div class="card-body">
<h3>Product Optimization for Ecommerce</h3>
<p>The more products you have, the more pages you have, and the larger your website is,
the more difficult it is to optimise. However, don't allow the store's massive size to deter
you from attracting customers. With effective product page optimization, you can turn
your pages into an asset. We concentrate on everything here, including on-page SEO,
image SEO, and product descriptions, to ensure that the user gets exactly what they
want.</p>
</div>
<!-- /.card-body -->
</div>
<!-- /.collapse -->
</div>

<div class="card">
<div class="card-header" id="accordion-heading-3-8">
<h5>
<button class="collapsed" data-toggle="collapse" data-target="#accordion-collapse-3-8" aria-expanded="false" aria-controls="accordion-collapse-3-8">Uninterrupted Navigation</button>
</h5>
</div>
<!-- /.card-header -->
<div id="accordion-collapse-3-8" class="collapse" aria-labelledby="accordion-heading-3-8" data-target="#accordion-3">
<div class="card-body">
<h3>Navigation on an Ecommerce Website</h3>
<p>Due to poor website navigation, many e-commerce sites have a significant bounce rate.
This is a straightforward yet critical part of any online store. Before making major
modifications, we make sure that the online store provides users with flawless,
error-free, and unambiguous navigation so that they can quickly find the information
they need.</p>
</div>
<!-- /.card-body -->
</div>
<!-- /.collapse -->
</div>

<div class="card">
<div class="card-header" id="accordion-heading-3-9">
<h5>
<button class="collapsed" data-toggle="collapse" data-target="#accordion-collapse-3-9" aria-expanded="false" aria-controls="accordion-collapse-3-9">For you, content that speaks volumes</button>
</h5>
</div>
<!-- /.card-header -->
<div id="accordion-collapse-3-9" class="collapse" aria-labelledby="accordion-heading-3-9" data-target="#accordion-3">
<div class="card-body">
<h3>Content Strategy for Ecommerce</h3>
<p>It's a half-hearted attempt to plan SEO without considering the content. We recognise
that it is the content that establishes a connection between you and your guests. We also
provide an e-commerce SEO content solution to make e-commerce SEO more effective.
We will handle all parts of the store's optimization, including product descriptions,
video content creation, and any other content creation and promotion.
This is the structure we use; we then personalise the approach based on our knowledge
and experience to make it more effective and result-oriented for our customers.</p>
</div>
<!-- /.card-body -->
</div>
<!-- /.collapse -->
</div>
</div>
          </div>
          <!--/column -->          
        </div>
        <!--/.row -->
      </div>
      <!-- /.container -->
    </div>

  <div class="wrapper light-wrapper">
      <div class="container inner">
        <div class="row align-items-center">
          <!--/column -->
          <div class="col-lg-6 pr-60 pr-md-15">
           <h3 class="display-3">When it comes to eCommerce SEO services, who should you hire?</h3>
            <p>eCommerce SEO services can help online stores with a wide range of products that are
dealing with ranking, traffic, and revenue. Our competitive and well-researched plan
will enhance ranking and income by addressing the weak areas.</p>
<p>Cost-Effective Lead Generation: Most e-commerce shops rely on paid advertising to
generate leads and sales. They may produce results, but only for a limited time and at a
great cost.</p>
<p>If you want a steady stream of clients and revenues without breaking the bank,
eCommerce SEO is the way to go.</p>
<p>Interested in learning more about our India-based eCommerce SEO firm?
In India, Four Phoenix is a well-known SEO firm. Make your online store more visible
on search engine result pages for relevant keywords, allowing you to attract more
customers and increase income. All of this is feasible with the help of an e-commerce
SEO specialist. Take the first step toward eCommerce SEO services by filling out the
form below. Now is the time to get a FREE Small Business SEO Consultation!</p>
          </div>
                             <div class="space30 d-none d-md-block d-lg-none"></div>

                     <div class="col-lg-6 play-wrapper light-gallery-wrapper text-center">
<div class="img-blob blob7"><img src="style/images/digital_marketing/e_commerce_seo.jpg" style="width: 30rem" alt="" /></div>
                      </div>

          <!--/column -->          
        </div>
        <!--/.row -->
      </div>
      <!-- /.container -->
    </div>
<?php include 'footer.php';?>

</div>
<!-- /.content-wrapper -->
<script src="style/js/jquery.min.js"></script>
<script src="style/js/popper.min.js"></script>
<script src="style/js/bootstrap.min.js"></script>
<script src="style/revolution/js/jquery.themepunch.tools.min.js"></script>
<script src="style/revolution/js/jquery.themepunch.revolution.min.js"></script>
<script src="style/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script src="style/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
<script src="style/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
<script src="style/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script src="style/revolution/js/extensions/revolution.extension.migration.min.js"></script>
<script src="style/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script src="style/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
<script src="style/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script src="style/revolution/js/extensions/revolution.extension.video.min.js"></script>
<script src="style/js/plugins.js"></script>
<script src="style/js/scripts.js"></script>
</body>
</html>